language: python

python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9

install:
    - pip install -r requirements.txt
    - pip install coverage==4.5.4
    - pip install python-coveralls

script:
    - coverage run --source=pdbsearch -m unittest discover tests

after_success:
  - coveralls
